Update continuous-integration.yml

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -39,11 +39,11 @@ jobs:
          pytest-tests-dir: .
          cov-threshold-total: 95
          
-#       - name: Coverage total fail - exit
-#         if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
-#         run: |
-#          echo "Coverage fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
-#          exit 1
+      - name: Coverage total fail - exit
+        if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+        run: |
+         echo "Coverage fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+         exit 1
          
       - name: Commit pytest coverage table
         uses: peter-evans/commit-comment@v1
